// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/http;

listener http:Listener ep0 = new (9090);

function buildOffer(string id, string origin, string destination, string total) returns FlightOffer => {
    'type: "flight-offer",
    id,
    'source: "GDS",
    instantTicketingRequired: false,
    nonHomogeneous: false,
    oneWay: false,
    lastTicketingDate: "2026-11-01",
    numberOfBookableSeats: 9,
    itineraries: [
        {
            duration: "PT9H10M",
            segments: [
                {
                    departure: {iataCode: origin, at: "2026-11-01T21:50:00"},
                    arrival: {iataCode: destination, at: "2026-11-02T08:45:00"},
                    carrierCode: "6X",
                    number: "188",
                    aircraft: {code: "777"},
                    operating: {carrierCode: "6X"},
                    duration: "PT9H10M",
                    id: "1",
                    numberOfStops: 0,
                    blacklistedInEU: false
                }
            ]
        }
    ],
    price: {currency: "EUR", total, base: "500.00"},
    pricingOptions: {fareType: ["PUBLISHED"], includedCheckedBagsOnly: true},
    validatingAirlineCodes: ["6X"],
    travelerPricings: [
        {
            travelerId: "1",
            fareOption: "STANDARD",
            travelerType: "ADULT",
            price: {currency: "EUR", total, base: "500.00"},
            fareDetailsBySegment: [
                {segmentId: "1", cabin: "ECONOMY", fareBasis: "EOBAA", 'class: "E", includedCheckedBags: {quantity: 1}}
            ]
        }
    ]
};

service /v2/shopping on ep0 {
    resource function get flight\-offers(string originLocationCode, string destinationLocationCode, string departureDate, string? returnDate, int? children, int? infants, "ECONOMY"|"PREMIUM_ECONOMY"|"BUSINESS"|"FIRST"? travelClass, string? includedAirlineCodes, string? excludedAirlineCodes, string? currencyCode, int? maxPrice, int adults = 1, boolean nonStop = false, int max = 250) returns FlightOffersResponse|Error400BadRequest|Error500Default {
        if originLocationCode == "XXX" {
            Error400BadRequest bad = {body: {errors: [{code: 477, title: "INVALID FORMAT", detail: "invalid origin location code", status: 400}]}};
            return bad;
        }
        FlightOffersResponse response = {
            meta: {
                count: 2,
                links: {self: "https://test.api.amadeus.com/v2/shopping/flight-offers?originLocationCode=" + originLocationCode + "&destinationLocationCode=" + destinationLocationCode}
            },
            data: [
                buildOffer("1", originLocationCode, destinationLocationCode, "546.40"),
                buildOffer("2", originLocationCode, destinationLocationCode, "612.15")
            ],
            dictionaries: {
                locations: {[originLocationCode]: {cityCode: originLocationCode, countryCode: "US"}, [destinationLocationCode]: {cityCode: destinationLocationCode, countryCode: "ES"}},
                aircraft: {"777": "BOEING 777-200/300"},
                currencies: {"EUR": "EURO"},
                carriers: {"6X": "AMADEUS SIX"}
            }
        };
        return response;
    }

    resource function post flight\-offers(@http:Payload GetFlightOffersQuery payload, @http:Header {name: "X-HTTP-Method-Override"} string xHTTPMethodOverride = "GET") returns FlightOffersSearchResponseOk|Error400BadRequest|Error500Default {
        if payload.originDestinations.length() == 0 {
            Error400BadRequest bad = {body: {errors: [{code: 32171, title: "MANDATORY DATA MISSING", detail: "originDestinations is required", status: 400}]}};
            return bad;
        }
        string origin = payload.originDestinations[0].originLocationCode ?: "MAD";
        string destination = payload.originDestinations[0].destinationLocationCode ?: "ATH";
        FlightOffersSearchResponseOk ok = {
            body: {
                meta: {count: 1},
                data: [buildOffer("1", origin, destination, "320.80")],
                dictionaries: {
                    locations: {[origin]: {cityCode: origin, countryCode: "ES"}, [destination]: {cityCode: destination, countryCode: "GR"}},
                    currencies: {"EUR": "EURO"},
                    carriers: {"6X": "AMADEUS SIX"}
                }
            }
        };
        return ok;
    }
}
// Service-mode response types. `bal openapi --mode client` collapses 4XX/5XX
// to `error` and never emits these, so they are defined here for the mock only.
public type Error400BadRequest record {|
    *http:BadRequest;
    Error400 body;
|};

public type Error500Default record {|
    *http:DefaultStatusCodeResponse;
    Error500 body;
|};

public type FlightOffersSearchResponseOk record {|
    *http:Ok;
    FlightOffersSearchResponse body;
|};

public type Error400 record {
    Issue[] errors;
};

public type Error500 record {
    Issue[] errors;
};
