// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/constraint;
import ballerina/http;

# OAuth2 Client Credentials Grant Configs
public type OAuth2ClientCredentialsGrantConfig record {|
    *http:OAuth2ClientCredentialsGrantConfig;
    # Token URL
    string tokenUrl = "https://test.api.amadeus.com/v1/security/oauth2/token";
|};

# traveler type
# age restrictions : CHILD < 12y, HELD_INFANT < 2y, SEATED_INFANT < 2y, SENIOR >=60y
public type TravelerType "ADULT"|"CHILD"|"SENIOR"|"YOUNG"|"HELD_INFANT"|"SEATED_INFANT"|"STUDENT";

public type Dictionaries record {
    AircraftEntry aircraft?;
    LocationEntry locations?;
    CarrierEntry carriers?;
    CurrencyEntry currencies?;
};

public type FlightOffersResponse record {
    Issue[] warnings?;
    CollectionMetaLink meta?;
    FlightOffer[] data;
    Dictionaries dictionaries?;
};

public type Issue record {
    # an application-specific error code
    int code?;
    # explanation of the error
    string detail?;
    # an object containing references to the source of the error
    IssueSource 'source?;
    # a short summary of the error
    string title?;
    # the HTTP status code applicable to this error
    int status?;
};

# Restriction towards number of connections
public type ConnectionRestriction record {
    # When this option is requested, recommendations made of Non-Stop flights only are favoured by the search, on the whole itinerary, with a weight of 75%
    boolean nonStopPreferred?;
    # The maximal number of connections for each itinerary. Value can be 0, 1 or 2
    decimal maxNumberOfConnections?;
    # This option allows the single segment to have one or more intermediate stops (technical stops)
    boolean technicalStopsAllowed?;
    # Allow to change airport during connection
    boolean airportChangeAllowed?;
};

public type AircraftEntry record {|
    string...;
|};

public type LocationEntry record {|
    LocationValue...;
|};

# a tax
public type Tax record {
    # Amount of the tax
    string amount?;
    # Code of the tax
    string code?;
};

# Additional services requested for the segment, such as chargeable checked bags, seats or other services
public type AdditionalServicesRequest record {
    # Details of chargeable checked bags
    ChargeableCheckedBags chargeableCheckedBags?;
    # DEPRECATED - use the chargeableSeat attribute -  seat number
    @constraint:String {pattern: re `[1-9][0-9]{0,2}[A-Z]?`}
    string chargeableSeatNumber?;
    # Other services to add
    ServiceName[] otherServices?;
    # Details of chargeable seat
    ChargeableSeat chargeableSeat?;
};

public type CurrencyEntry record {|
    string...;
|};

public type TravelerInfo record {
    # traveler type
    # age restrictions : CHILD < 12y, HELD_INFANT < 2y, SEATED_INFANT < 2y, SENIOR >=60y
    TravelerType travelerType;
    # if type="HELD_INFANT", corresponds to the adult travelers's id who will share the seat
    string associatedAdultId?;
    string id;
};

# an object containing references to the source of the error
public type IssueSource record {
    # a JSON Pointer [RFC6901] to the associated entity in the request document
    string pointer?;
    # a string indicating which URI query parameter caused the issue
    string 'parameter?;
    # a string indicating an example of the right value
    string example?;
};

public type Itinerary record {
    # duration in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) PnYnMnDTnHnMnS format, e.g. PT2H10M for a duration of 2h10m
    string duration?;
    @constraint:Array {maxLength: 9, minLength: 1}
    Segment[] segments;
};

public type LocationValue record {
    # City code associated to the airport
    string cityCode?;
    # Country code of the airport
    string countryCode?;
};

public type FlightOffer record {
    # If true, a payment card is mandatory to book this flight offer
    boolean paymentCardRequired?;
    # Number of seats bookable in a single request. Can not be higher than 9
    @constraint:Number {minValue: 1, maxValue: 9}
    decimal numberOfBookableSeats?;
    # Fare information for each traveler/segment
    @constraint:Array {maxLength: 18, minLength: 1}
    TravelerPricing[] travelerPricings?;
    # If true, inform that a ticketing will be required at booking step
    boolean instantTicketingRequired?;
    # This option ensures that the system will only consider offers with these airlines as validating carrier
    @constraint:Array {maxLength: 9, minLength: 1}
    string[] validatingAirlineCodes?;
    # BOOK step ONLY - If true, allows to book a PNR without pricing. Only for the source "GDS"
    boolean disablePricing?;
    # source of the flight offer
    FlightOfferSource 'source?;
    # the resource name
    string 'type;
    # If true, the flight offer can be combined with other oneWays flight-offers to complete the whole journey (one-Way combinable feature)
    boolean oneWay?;
    # price information
    ExtendedPrice price?;
    PricingOptions pricingOptions?;
    # If true, upon completion of the booking, this pricing solution is expected to yield multiple records (a record contains booking information confirmed and stored, typically a Passenger Name Record (PNR), in the provider GDS or system)
    boolean nonHomogeneous?;
    @constraint:Array {maxLength: 250, minLength: 1}
    Itinerary[] itineraries?;
    # If booked on the same day as the search (with respect to timezone), this flight offer is guaranteed to be thereafter valid for ticketing until this date (included). Unspecified when it does not make sense for this flight offer (e.g. no control over ticketing once booked). YYYY-MM-DD format, e.g. 2019-06-07
    string lastTicketingDate?;
    # Id of the flight offer
    string id;
    # If booked on the same day as the search (with respect to timezone), this flight offer is guaranteed to be thereafter valid for ticketing until this date/time (included). Unspecified when it does not make sense for this flight offer (e.g. no control over ticketing once booked). Information only this attribute is not used in input of pricing request. Local date and time in YYYY-MM-ddThh:mm:ss format, e.g. 2017-02-10T20:40:00
    string lastTicketingDateTime?;
};

# Provides a set of configurations for controlling the behaviours when communicating with a remote HTTP endpoint.
@display {label: "Connection Config"}
public type ConnectionConfig record {|
    # Configurations related to client authentication
    OAuth2ClientCredentialsGrantConfig auth;
    # The HTTP version understood by the client
    http:HttpVersion httpVersion = http:HTTP_2_0;
    # Configurations related to HTTP/1.x protocol
    http:ClientHttp1Settings http1Settings = {};
    # Configurations related to HTTP/2 protocol
    http:ClientHttp2Settings http2Settings = {};
    # The maximum time to wait (in seconds) for a response before closing the connection
    decimal timeout = 30;
    # The choice of setting `forwarded`/`x-forwarded` header
    string forwarded = "disable";
    # Configurations associated with Redirection
    http:FollowRedirects followRedirects?;
    # Configurations associated with request pooling
    http:PoolConfiguration poolConfig?;
    # HTTP caching related configurations
    http:CacheConfig cache = {};
    # Specifies the way of handling compression (`accept-encoding`) header
    http:Compression compression = http:COMPRESSION_AUTO;
    # Configurations associated with the behaviour of the Circuit Breaker
    http:CircuitBreakerConfig circuitBreaker?;
    # Configurations associated with retrying
    http:RetryConfig retryConfig?;
    # Configurations associated with cookies
    http:CookieConfig cookieConfig?;
    # Configurations associated with inbound response size limits
    http:ResponseLimitConfigs responseLimits = {};
    # SSL/TLS-related options
    http:ClientSecureSocket secureSocket?;
    # Proxy server related options
    http:ProxyConfig proxy?;
    # Provides settings related to client socket configuration
    http:ClientSocketConfig socketConfig = {};
    # Enables the inbound payload validation functionality which provided by the constraint package. Enabled by default
    boolean validation = true;
    # Enables relaxed data binding on the client side. When enabled, `nil` values are treated as optional, 
    # and absent fields are handled as `nilable` types. Enabled by default.
    boolean laxDataBinding = true;
|};

public type OriginDestinationLight record {
    # Destination location, such as a city or an airport. Currently, only the locations defined in [IATA](http://www.iata.org/publications/Pages/code-search.aspx) are supported
    string destinationLocationCode?;
    # List of included connections points. When an includedViaPoints option is specified, all FlightOffer returned must at least go via this Connecting Point. Currently, only the locations defined in IATA are supported. Used only by the AMADEUS provider
    @constraint:Array {maxLength: 2, minLength: 1}
    string[] includedConnectionPoints?;
    # Origin location, such as a city or an airport. Currently, only the locations defined in [IATA](http://www.iata.org/publications/Pages/code-search.aspx) are supported
    string originLocationCode?;
    string id?;
    # List of excluded connections points. Any FlightOffer with these connections points will be present in response. Currently, only the locations defined in IATA are supported. Used only by the AMADEUS provider
    @constraint:Array {maxLength: 3, minLength: 1}
    string[] excludedConnectionPoints?;
};

# Details of chargeable seat
public type ChargeableSeat record {
    # seat number
    @constraint:String {pattern: re `[1-9][0-9]{0,2}[A-Z]?`}
    string number?;
    # Id of the chargeable seat
    string id?;
};

# quality of service offered in the cabin where the seat is located in this flight. Economy, premium economy, business or first class
public type TravelClass "ECONOMY"|"PREMIUM_ECONOMY"|"BUSINESS"|"FIRST";

# departure or arrival information
public type FlightEndPoint record {
    *OriginalFlightEndPoint;
    # local date and time in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) YYYY-MM-ddThh:mm:ss format, e.g. 2017-02-10T20:40:00
    string at?;
};

# departure or arrival information
public type OriginalFlightEndPoint record {
    # [IATA airline codes](http://www.iata.org/publications/Pages/code-search.aspx)
    string iataCode?;
    # terminal name / number
    string terminal?;
};

# details of stops for direct or change of gauge flights
public type OriginalFlightStop record {
    # stop duration in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) PnYnMnDTnHnMnS format, e.g. PT2H10M
    string duration?;
    # [IATA airline codes](http://www.iata.org/publications/Pages/code-search.aspx)
    string iataCode?;
};

public type CollectionLinks record {
    string next?;
    string previous?;
    string last?;
    string self?;
    string up?;
    string first?;
};

# Fare details of the segment
public type FareDetailsBySegment record {
    # True if the corresponding booking class is in an allotment
    boolean isAllotment?;
    # Additional services requested for the segment, such as chargeable checked bags, seats or other services
    AdditionalServicesRequest additionalServices?;
    # baggageAllowance
    BaggageAllowance includedCheckedBags?;
    # Fare basis specifying the rules of a fare. Usually, though not always, is composed of the booking class code followed by a set of letters and digits representing other characteristics of the ticket, such as refundability, minimum stay requirements, discounts or special promotional elements
    string fareBasis?;
    # Id of the segment
    string segmentId;
    # quality of service offered in the cabin where the seat is located in this flight. Economy, premium economy, business or first class
    TravelClass cabin?;
    # The code of the booking class, a.k.a. class of service or Reservations/Booking Designator (RBD)
    @constraint:String {pattern: re `[A-Z]{1}`}
    string 'class?;
    # slice and Dice indicator, such as Local Availability, Sub OnD(Origin and Destination) 1 Availability and Sub OnD 2 Availability
    SliceDiceIndicator sliceDiceIndicator?;
    # The name of the Fare Family corresponding to the fares. Only for the GDS provider and if the airline has fare families filled
    string brandedFare?;
    # Details of the allotment the booking class belongs to
    AllotmentDetails allotmentDetails?;
};

public type CollectionMeta record {
    int count?;
    OneWayCombinations[] oneWayCombinations?;
};

public type DateTimeType record {
    # Dates are specified in the [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) YYYY-MM-DD format, e.g. 2018-12-25
    string date;
    # Local time. hh:mm:ss format, e.g 10:30:00
    string time?;
};

# Represents the Queries record for the operation: getFlightOffers
public type GetFlightOffersQueries record {
    # the number of infant travelers (whose age is less or equal to 2 on date of departure). Infants travel on the lap of an adult traveler, and thus the number of infants must not exceed the number of adults. If specified, this number should be greater than or equal to 0
    @constraint:Int {minValue: 0, maxValue: 9}
    int infants?;
    # if set to true, the search will find only flights going from the origin to the destination with no stop in between
    boolean nonStop = false;
    # city/airport [IATA code](http://www.iata.org/publications/Pages/code-search.aspx) to which the traveler is going, e.g. PAR for Paris
    @constraint:String {pattern: re `[A-Z]{3}`}
    string destinationLocationCode;
    # maximum number of flight offers to return. If specified, the value should be greater than or equal to 1
    @constraint:Int {minValue: 1}
    int max = 250;
    # the number of adult travelers (age 12 or older on date of departure).
    # 
    # The total number of seated travelers (adult and children) can not exceed 9
    @constraint:Int {minValue: 1, maxValue: 9}
    int adults = 1;
    # This option ensures that the system will ignore these airlines. This can not be cumulated with parameter includedAirlineCodes.
    # 
    # Airlines are specified as [IATA airline codes](http://www.iata.org/publications/Pages/code-search.aspx) and are comma-separated, e.g. 6X,7X,8X
    @constraint:String {pattern: re `[0-9A-Z]{2}`}
    string excludedAirlineCodes?;
    # most of the flight time should be spent in a cabin of this quality or higher. The accepted travel class is economy, premium economy, business or first class. If no travel class is specified, the search considers any travel class
    "ECONOMY"|"PREMIUM_ECONOMY"|"BUSINESS"|"FIRST" travelClass?;
    # the date on which the traveler will depart from the destination to return to the origin. If this parameter is not specified, only one-way itineraries are found. If this parameter is specified, only round-trip itineraries are found. Dates are specified in the [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) YYYY-MM-DD format, e.g. 2018-02-28
    string returnDate?;
    # the number of child travelers (older than age 2 and younger than age 12 on date of departure) who will each have their own separate seat. If specified, this number should be greater than or equal to 0
    # 
    # The total number of seated travelers (adult and children) can not exceed 9
    @constraint:Int {minValue: 0, maxValue: 9}
    int children?;
    # city/airport [IATA code](http://www.iata.org/publications/Pages/code-search.aspx) from which the traveler will depart, e.g. BOS for Boston
    @constraint:String {pattern: re `[A-Z]{3}`}
    string originLocationCode;
    # the date on which the traveler will depart from the origin to go to the destination. Dates are specified in the [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) YYYY-MM-DD format, e.g. 2017-12-25
    string departureDate;
    # maximum price per traveler. By default, no limit is applied. If specified, the value should be a positive number with no decimals
    @constraint:Int {minValue: 1}
    int maxPrice?;
    # the preferred currency for the flight offers. Currency is specified in the [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) format, e.g. EUR for Euro
    @constraint:String {pattern: re `[A-Z]{3}`}
    string currencyCode?;
    # This option ensures that the system will only consider these airlines. This can not be cumulated with parameter excludedAirlineCodes.
    # 
    # Airlines are specified as [IATA airline codes](http://www.iata.org/publications/Pages/code-search.aspx) and are comma-separated, e.g. 6X,7X,8X
    @constraint:String {pattern: re `[0-9A-Z]{2}`}
    string includedAirlineCodes?;
};

public type Price record {
    # Total amount paid by the user
    string total?;
    # List of applicable fees
    Fee[] fees?;
    Tax[] taxes?;
    string currency?;
    # The amount of taxes which are refundable
    string refundableTaxes?;
    # Amount without taxes
    string base?;
};

# type of service
public type ServiceName "PRIORITY_BOARDING"|"AIRPORT_CHECKIN";

public type OriginDestination record {
    *OriginDestinationLight;
    DateTimeRange departureDateTimeRange?;
    # Set of alternative destination location, such as a city or an airport. Currently, only the locations defined in [IATA](http://www.iata.org/publications/Pages/code-search.aspx) are supported
    string[] alternativeDestinationsCodes?;
    DateTimeRange arrivalDateTimeRange?;
    # Include other possible locations around the point, located less than this distance in kilometers away. Max:300
    # 
    # Can not be combined with "dateWindow" or "timeWindow"
    decimal originRadius?;
    # Set of alternative origin location, such as a city or an airport. Currently, only the locations defined in [IATA](http://www.iata.org/publications/Pages/code-search.aspx) are supported
    string[] alternativeOriginsCodes?;
    # Include other possible locations around the point, located less than this distance in kilometers away. Max:300
    # 
    # Can not be combined with "dateWindow" or "timeWindow"
    decimal destinationRadius?;
};

# Restriction towards carriers
public type CarrierRestrictions record {
    # This option ensures that the system will only consider these airlines
    @constraint:Array {maxLength: 99, minLength: 1}
    string[] includedCarrierCodes?;
    # This option ensures that the system will only consider these airlines
    @constraint:Array {maxLength: 99, minLength: 1}
    string[] excludedCarrierCodes?;
    # This flag enable/disable filtering of blacklisted airline by EU. The list of the banned airlines is published in the Official Journal of the European Union, where they are included as annexes A and B to the Commission Regulation. The blacklist of an airline can concern all its flights or some specific aircraft types pertaining to the airline
    boolean blacklistedInEUAllowed = false;
};

# Details of chargeable checked bags
public type ChargeableCheckedBags record {
    *BaggageAllowance;
    # Id of the chargeable bag
    string id?;
};

# source of the flight offer
public type FlightOfferSource "GDS";

public type FlightOffersSearchResponse record {
    Issue[] warnings?;
    CollectionMeta meta?;
    FlightOffer[] data;
    Dictionaries dictionaries?;
};

# details of stops for direct or change of gauge flights
public type FlightStop record {
    *OriginalFlightStop;
    # departure from the stop in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) YYYY-MM-ddThh:mm:ss format, e.g. 2017-02-10T20:40:00
    string departureAt?;
    # arrival at the stop in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) YYYY-MM-ddThh:mm:ss format, e.g. 2017-02-10T20:40:00
    string arrivalAt?;
};

# Represents the Headers record for the operation: searchFlightOffers
public type SearchFlightOffersHeaders record {
    # the HTTP method to apply
    @http:Header {name: "X-HTTP-Method-Override"}
    string xHTTPMethodOverride = "GET";
};

# type of fee
public type FeeType "TICKETING"|"FORM_OF_PAYMENT"|"SUPPLIER";

public type AdditionalService record {
    string amount?;
    # additional service type
    AdditionalServiceType 'type?;
};

# Details of the allotment the booking class belongs to
public type AllotmentDetails record {
    # The tour name agreed for this specific allotment
    string tourName?;
    # The tour reference agreed for this specific allotment
    string tourReference?;
};

public type GetFlightOffersQuery record {
    # Allows enable one or more sources. If present in the list, these sources will be called by the system
    @constraint:Array {minLength: 1}
    FlightOfferSource[] sources;
    SearchCriteria searchCriteria?;
    # Origins and Destinations must be properly ordered in time (chronological order in accordance with the timezone of each location) to describe the journey consistently. Dates and times must not be past nor more than 365 days in the future, according to provider settings.Number of Origins and Destinations must not exceed the limit defined in provider settings
    @constraint:Array {maxLength: 6, minLength: 1}
    OriginDestination[] originDestinations;
    # The currency code, as defined in [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217), to reflect the currency in which this amount is expressed
    string currencyCode?;
    # travelers in the trip. 
    # 
    #  Maximum number of passengers older than 2 yo (CHILD, ADULT, YOUGHT): 9.
    #  Each adult can travel with one INFANT so maximum total number of passengers: 18
    @constraint:Array {maxLength: 18, minLength: 1}
    ExtendedTravelerInfo[] travelers;
};

public type PricingOptions record {
    # If true, returns the flight-offers with included checked bags only
    boolean includedCheckedBagsOnly?;
    # If true, returns the flight-offers with no restriction fares only
    boolean noRestrictionFare?;
    # If true, returns the flight-offers with no penalty fares only
    boolean noPenaltyFare?;
    # type of fare of the flight-offer
    PricingOptionsFareType fareType?;
    # If true, returns the flight-offers with refundable fares only
    boolean refundableFare?;
};

public type Co2Emission record {
    # Weight of Co2 emitted for the concerned segment
    int weight?;
    # quality of service offered in the cabin where the seat is located in this flight. Economy, premium economy, business or first class
    TravelClass cabin?;
    # Code to qualify unit as pounds or kilos
    string weightUnit?;
};

public type Segment record {
    # Number of stops planned on the segment for technical or operation purpose i.e. refueling
    int numberOfStops?;
    # When the flight has a marketing or/and operating airline that is identified as blacklisted by the European Commission. 
    # 
    # To improve travel safety, the European Commission regularly updates the list of the banned carriers from operating in Europe. It allows any Travel Agency located in the European Union to easily identify and hide any travel recommendation based on some unsafe airlines. 
    # The [list of the banned airlines](https://ec.europa.eu/transport/sites/transport/files/air-safety-list_en.pdf) is published in the Official Journal of the European Union, where they are included as annexes A and B to the Commission Regulation. The blacklist of an airline can concern all its flights or some specific aircraft types pertaining to the airline   
    boolean blacklistedInEU?;
    # Id of the segment
    string id?;
    # Co2 informations
    Co2Emission[] co2Emissions?;
    *FlightSegment;
};

# defining a flight segment; including both operating and marketing details when applicable
public type FlightSegment record {
    # stop duration in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) PnYnMnDTnHnMnS format, e.g. PT2H10M
    string duration?;
    # the flight number as assigned by the carrier
    @constraint:String {maxLength: 4, minLength: 1}
    string number?;
    # departure or arrival information
    FlightEndPoint arrival?;
    # providing the airline / carrier code
    @constraint:String {maxLength: 2, minLength: 1}
    string carrierCode?;
    # information related to the aircraft
    AircraftEquipment aircraft?;
    # departure or arrival information
    FlightEndPoint departure?;
    # information about the operating flight
    OperatingFlight operating?;
    # information regarding the different stops composing the flight segment. E.g. technical stop, change of gauge..
    FlightStop[] stops?;
};

# price information
public type ExtendedPrice record {
    # Prices of the additional services
    AdditionalService[] additionalServices?;
    # BOOK step ONLY - The price margin percentage (plus or minus) that the booking can tolerate. When set to 0, then no price magin is tolerated
    string margin?;
    # Total amount paid by the user (including fees and selected additional services)
    string grandTotal?;
    # Currency of the payment. It may be different than the requested currency
    string billingCurrency?;
    *Price;
};

public type CollectionMetaLink record {
    int count?;
    CollectionLinks links?;
};

public type ExtendedCabinRestriction record {
    *CabinRestriction;
    # part of the trip covered by the travel class restriction (ALL_SEGMENTS if ommited)
    Coverage coverage?;
};

public type DateTimeRange record {
    *DateTimeType;
    # Either 1, 2 or 3 extra days around the local date (IxD for +/- x days - Ex: I3D), Either 1 to 3 days after the local date (PxD for +x days - Ex: P3D), or 1 to 3 days before the local date (MxD for -x days - Ex: M3D)
    # 
    # Can not be combined with "originRadius" or "destinationRadius"
    string dateWindow?;
    # 1 to 12 hours around (both +and -) the local time. Possibly limited by the number of extra days when specified, i.e.  in some situations, it may not be used to exceed the maximum date range. [1-12]H format, e.g. 6H
    # 
    # Can not be combined with "originRadius" or "destinationRadius"
    string timeWindow?;
};

# fare filter options
public type ExtendedPricingOptions record {
    # If true, returns the flight-offers with included checked bags only
    boolean includedCheckedBagsOnly?;
    # If true, returns the flight-offers with no restriction fares only
    boolean noRestrictionFare?;
    # If true, returns the flight-offers with no penalty fares only
    boolean noPenaltyFare?;
    # If true, returns the flight-offers with refundable fares only
    boolean refundableFare?;
};

# information related to the aircraft
public type AircraftEquipment record {
    # IATA aircraft code (http://www.flugzeuginfo.net/table_accodes_iata_en.php)
    @constraint:String {pattern: re `[a-zA-Z0-9]{3}`}
    string code?;
};

public type AdditionalInformation record {
    # If true, returns the fare family name for each flight-offer which supports fare family
    boolean brandedFares?;
    # If true, returns the price of the first additional bag when the airline is an "Amadeus Ancillary Services" member
    boolean chargeableCheckedBags?;
};

public type CabinRestriction record {
    # The list of originDestination identifiers for which the cabinRestriction applies
    string[] originDestinationIds?;
    # quality of service offered in the cabin where the seat is located in this flight. Economy, premium economy, business or first class
    TravelClass cabin?;
};

public type ExtendedTravelerInfo TravelerInfo;

# a fee
public type Fee record {
    # Amount of the fee
    string amount?;
    # type of fee
    FeeType 'type?;
};

public type TravelerPricing record {
    # traveler type
    # age restrictions : CHILD < 12y, HELD_INFANT < 2y, SEATED_INFANT < 2y, SENIOR >=60y
    TravelerType travelerType;
    Price price?;
    # if type="HELD_INFANT", corresponds to the adult traveler's id who will share the seat
    string associatedAdultId?;
    # option specifying a group of fares, which may be valid under certain conditons
    # Can be used to specify special fare discount for a passenger
    TravelerPricingFareOption fareOption;
    @constraint:Array {maxLength: 18, minLength: 1}
    FareDetailsBySegment[] fareDetailsBySegment;
    # Id of the traveler
    string travelerId;
};

# part of the trip covered by the travel class restriction (ALL_SEGMENTS if ommited)
public type Coverage "MOST_SEGMENTS"|"AT_LEAST_ONE_SEGMENT"|"ALL_SEGMENTS";

# slice and Dice indicator, such as Local Availability, Sub OnD(Origin and Destination) 1 Availability and Sub OnD 2 Availability
public type SliceDiceIndicator "LOCAL_AVAILABILITY"|"SUB_OD_AVAILABILITY_1"|"SUB_OD_AVAILABILITY_2";

# type of fare of the flight-offer
public type PricingOptionsFareType ("PUBLISHED"|"NEGOTIATED"|"CORPORATE")[];

public type SearchCriteria record {
    # This option allows to exclude the isAllotment flag associated to a booking class in the search response when it exist
    boolean excludeAllotments?;
    AdditionalInformation additionalInformation?;
    # This option allows to default to a standard fareOption if no offers are found for the selected fareOption
    boolean allowAlternativeFareOptions?;
    # Requests the system to find at least one flight-offer per day, if possible, when a range of dates is specified. Default is false
    boolean oneFlightOfferPerDay?;
    FlightFilters flightFilters?;
    # fare filter options
    ExtendedPricingOptions pricingOptions?;
    # This option allows activate the one-way combinable feature
    boolean addOneWayOffers?;
    # Maximum number of flight offers returned (Max 250)
    decimal maxFlightOffers?;
    # maximum price per traveler. By default, no limit is applied. If specified, the value should be a positive number with no decimals
    int maxPrice?;
};

# information about the operating flight
public type OperatingFlight record {
    # providing the airline / carrier code
    @constraint:String {maxLength: 2, minLength: 1}
    string carrierCode?;
};

public type OneWayCombinations record {
    string originDestinationId?;
    string[] flightOfferIds?;
};

public type FlightFilters record {
    # This flag enable/disable filtering of bus segment
    boolean busSegmentAllowed?;
    # Maximum flight time as a percentage relative to the shortest flight time available for the itinerary
    decimal maxFlightTime?;
    # Restriction towards cabins
    @constraint:Array {maxLength: 6, minLength: 1}
    ExtendedCabinRestriction[] cabinRestrictions?;
    # Restriction towards number of connections
    ConnectionRestriction connectionRestriction?;
    # This option force to retrieve flight-offer with a departure and a return in the same airport
    boolean returnToDepartureAirport?;
    # Restriction towards carriers
    CarrierRestrictions carrierRestrictions?;
    # This flag enable/disable filtering of rail segment (TGV AIR, RAIL ...)
    boolean railSegmentAllowed?;
    # This flag enables/disables the possibility to have more overnight flights in Low Fare Search
    boolean moreOvernightsAllowed?;
    # Allows to search a location outside the borders when a radius around a location is specified. Default is false
    boolean crossBorderAllowed?;
};

# additional service type
public type AdditionalServiceType "CHECKED_BAGS"|"MEALS"|"SEATS"|"OTHER_SERVICES";

public type CarrierEntry record {|
    string...;
|};

# option specifying a group of fares, which may be valid under certain conditons
# Can be used to specify special fare discount for a passenger
public type TravelerPricingFareOption "STANDARD"|"INCLUSIVE_TOUR"|"SPANISH_MELILLA_RESIDENT"|"SPANISH_CEUTA_RESIDENT"|"SPANISH_CANARY_RESIDENT"|"SPANISH_BALEARIC_RESIDENT"|"AIR_FRANCE_METROPOLITAN_DISCOUNT_PASS"|"AIR_FRANCE_DOM_DISCOUNT_PASS"|"AIR_FRANCE_COMBINED_DISCOUNT_PASS"|"AIR_FRANCE_FAMILY"|"ADULT_WITH_COMPANION"|"COMPANION";

# baggageAllowance
public type BaggageAllowance record {
    # Total number of units
    int quantity?;
    # Weight of the baggage allowance
    int weight?;
    # Code to qualify unit as pounds or kilos
    string weightUnit?;
};
